### ISSUE TITLE
Connect API response data to Room database

### ISSUE THREAD

**Issue by unicornsleuth** [dansjack/covid-score-app#18]
The information that is returned from the API calls is parsed into our classes, Location and CovidSnapshot. 
As the objects are created (currently with placeholder data), they are added to the Room database.
The Room data is now accessible through the ViewModel, named vm in MainActivity.java
For the purposes of this issue, I am just editing the central TextView to show the (relatively unformatted) Room data.

**Comment by dansjack** [comment]
Completed
