### ISSUE TITLE
Set up Circle CI

### ISSUE THREAD

**Issue by chonger878** [dansjack/covid-score-app#4]
Set up Circle CI for testing the app.

**Comment by Ameenrehman** [comment]
hello,can you please tell me what to do in this isue

**Comment by chonger878** [comment]
Greetings Ameenrehman, this is actually for a school project. Unfortunately, we cannot accept outside contributions. We apologize deeply for any confusion.

**Comment by Ameenrehman** [comment]
Aah no problem @chonger878

**Comment by dansjack** [comment]
CircleCI is set up. If you're unable to view CircleCI or codecov, please let me know. I may need to adjust permissions.
