### ISSUE TITLE
Bug fix: Welcome text and card view cut off

### ISSUE THREAD

**Issue by AllisonBC** [dansjack/covid-score-app#67]
### Context
Fixes the bug that cuts off the bottom of the card view on 'RDPF'.  Updates app so that the welcome message only appears if there is no stored snapshots. 

### Acceptance Criteria
- [x] Last card bottom no longer cut off
- [x] Welcome message only appears on first use/when there is no stored snapshot

**Comment by dansjack** [comment]
Completed
